// Mocks generated by Mockito 5.4.2 from annotations
// in ditonton/test/presentation/bloc/watchlist_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:core/necessary_utils.dart' as _i6;
import 'package:dartz/dartz.dart' as _i2;
import 'package:ditonton/domain/usecase/get_watchlist_movies.dart' as _i4;
import 'package:ditonton/domain/usecase/get_watchlist_series.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movies/necessary_entities.dart' as _i7;
import 'package:tvseries/necessary_entities.dart' as _i9;
import 'package:tvseries/necessary_usecases.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSeriesRepository_1 extends _i1.SmartFake
    implements _i3.SeriesRepository {
  _FakeSeriesRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetWatchlistMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistMovies extends _i1.Mock
    implements _i4.GetWatchlistMovies {
  MockGetWatchlistMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.Movie>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, List<_i7.Movie>>>.value(
            _FakeEither_0<_i6.Failure, List<_i7.Movie>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.Movie>>>);
}

/// A class which mocks [GetWatchlistSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistSeries extends _i1.Mock
    implements _i8.GetWatchlistSeries {
  MockGetWatchlistSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SeriesRepository get seriesRepository => (super.noSuchMethod(
        Invocation.getter(#seriesRepository),
        returnValue: _FakeSeriesRepository_1(
          this,
          Invocation.getter(#seriesRepository),
        ),
      ) as _i3.SeriesRepository);
  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i9.Series>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, List<_i9.Series>>>.value(
                _FakeEither_0<_i6.Failure, List<_i9.Series>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, List<_i9.Series>>>);
}
