// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0vooFzm0vgsjoE2aNIee8kquF5PmLXws',
    appId: '1:792248497147:web:b77cce579367c2dc63115e',
    messagingSenderId: '792248497147',
    projectId: 'dicodinge-expert',
    authDomain: 'dicodinge-expert.firebaseapp.com',
    storageBucket: 'dicodinge-expert.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7W9luqRkyUJ645b_ALztLBaz-L30a8o4',
    appId: '1:792248497147:android:7999a4ade14093fe63115e',
    messagingSenderId: '792248497147',
    projectId: 'dicodinge-expert',
    storageBucket: 'dicodinge-expert.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkc5mrmxOg2tyu-jn5r8JV-I6kYUa45yI',
    appId: '1:792248497147:ios:4da95eaa7876573963115e',
    messagingSenderId: '792248497147',
    projectId: 'dicodinge-expert',
    storageBucket: 'dicodinge-expert.appspot.com',
    iosBundleId: 'com.dicoding.flutterExpertProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkc5mrmxOg2tyu-jn5r8JV-I6kYUa45yI',
    appId: '1:792248497147:ios:52ee0123b3c040c063115e',
    messagingSenderId: '792248497147',
    projectId: 'dicodinge-expert',
    storageBucket: 'dicodinge-expert.appspot.com',
    iosBundleId: 'com.dicoding.flutterExpertProject.RunnerTests',
  );
}
